export const FETCH_USER = "fetch_user"
export const FETCH_SURVEYS = "fetch_surveys"
export const FETCH_BLOGS = "fetch_blogs"
export const FETCH_BLOG_DETAIL = "fetch_blog_detail"
export const FETCH_COMMENTS = "fetch_comments"
export const SUBMIT_COMMENT = "submit_comment"
